############################
## CHANGE THESE
############################

baseURL: "https://LordSudo.github.io/qubttest"
title: qubttest

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
